### ISSUE TITLE
Mislabled plot in example 7.6

### ISSUE THREAD

**Issue by msmeta** [uu-sml/sml-book-page#10]
**Location**
Please provide:
1. Version: February 10, 2020
2. Page number: 112
3. Line/equation number: Lables in the first plots

**Describe the mistake**
Both plots for AdaBoost are labled with tree depth 3
**Suggested change**
It is suggested in the text that one of them should have depth 1

**Comment by nikwa** [comment]
Yes, you are correct, first one should be depth 1, will be corrected.
