### ISSUE TITLE
Some typos I’ve found

### ISSUE THREAD

**Issue by OskarTegby** [uu-sml/sml-book-page#11]
On line 1 of page 90 in the draft of February 14 the word “vectorized” is misspelled as “vecotrized“. It should say “vectorized”.

**Comment by OskarTegby** [comment]
The word “languages” is also misspelled on that page as “laguages”. That is, draft January 18, page 90, line 1.

**Comment by OskarTegby** [comment]
Yet another word misspelled on line 24 on page 90 in the draft of January 18. The word “which” is spelled as “witch”.

**Comment by OskarTegby** [comment]
On line 3 (in the figure text of Figure 6.13) in page 98 (in the draft of January 18), the word “were” is misspelled as “where”. They are homophones, but not synonyms.

**Comment by OskarTegby** [comment]
Mismatched parenthesis in the subsection “Dropout as a regularization method” on page 98 in the draft of January 18.

**Comment by OskarTegby** [comment]
Mismatched parenthesis in the subsection “Dropout as a regularization method” on page 98 in the draft of January 18.

**Comment by OskarTegby** [comment]
On page 141 on line 3, in the draft of February 14, the sentence “The most commonly method corresponds to finding the projection that maximizes the variance of the projected data.” lacks the word “used”. It is supposed to say “The most commonly used method (...)”, but it only says “The most commonly method (...)”.

**Comment by nikwa** [comment]
Thanks for spotting these typos!
