### ISSUE TITLE
Typing mistake

### ISSUE THREAD

**Issue by SeemaNegi** [uu-sml/sml-book-page#15]
**Location**
1.  Version:- Draft (June 17, 2020) of Supervised Machine Learning. Feedback and exercise problems.
2.  Page No.:- 44
3.  Line:- 3rd Paragraph, 2 line

![end_typo](https://user-images.githubusercontent.com/41466478/86181509-6b38dd80-bb2e-11ea-9122-4adca580e4a8.PNG)

**Description of the mistake and suggested change:-**
 
**end** should be replaced by **and**

**Comment by andreas-lindholm** [comment]
Thank you for pointing this out, it will be updated in the next version.
