### ISSUE TITLE
Huber loss is incorrect

### ISSUE THREAD

**Issue by joakimlindblad** [uu-sml/sml-book-page#17]
**Location**
Please provide:
1. Version: Draft (October 27, 2020) of Supervised Machine Learning.
2. Page number: 70
3. Line/equation number: Eq. (5.4) and Fig. 5.1

**Describe the mistake**
Huber loss is strongly convex, which the curve in Fig. 5.1 clearly is not.
You've got the wrong eq. in 5.4; multiply the squared part by 0.5, and subtract 0.5 from the linear part.

**Suggested change**
See e.g. https://en.wikipedia.org/wiki/Huber_loss

**Additional comments**
Keep up the great work!

**Comment by andreas-lindholm** [comment]
That's correct, will be fixed in next version! Thanks.
