### ISSUE TITLE
Notation of Euclidean norm

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#18]
Hi! In section "2.2 A distance-based method: k-NN" Euclidean norm is notated without the subscript of 2 and is not explicitly explained. Later in section "Least squares and the normal equations" it is notated with a subscript and is explained. This may be inconsistent. (SML Draft version: October 29, 2020)

**Comment by nikwa** [comment]
In k-NN you don't necessarily have to use the L2 norm, but in least squares using the L2 norm is included in the definition. However, I agree that this could be clarified. We will consider that for the next version. Thanks for the comment!

**Comment by andreas-lindholm** [comment]
Thanks for the feedback! It has now been updated.
