### ISSUE TITLE
"Dummy variable trap" in regression models

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#19]
Consider adding a note about the "dummy variable trap" into the "Categorical input variables" section (chapter "3.1 Linear regression"). Some people use the "dummy variable trap" name to describe a situation when not removing one of the levels of a categorical variable leads to a perfect multi-collinearity in the regression model if an intercept is included. I.e. a sum of all levels is always 1 and equals the first column of the design matrix, which represents the intercept. Thank you! 
(SML Draft version: October 29, 2020)

**Comment by devmotion** [comment]
Copying from my comment on Studium:

> In general, however, to me it seems the dummy variable trap is only a trap in descriptive statistics, i.e., if you want to inspect the parameters and reason about the significance of each feature. If you are only interested in making predictions as it is often the case in machine learning, then the collinearity due to one-hot encodings does not matter. It is common (not only in scikit-learn) to use one (of the inifinitely many) solution to the normal equations in such a case; typically the one which minimizes the Euclidean norm of the parameters is taken, as mentioned by Calle (e.g., in the [LAPACK](http://netlib.org/lapack/lug/node27.html) library). Since the same dependence between the features will exist in the one-hot encoded test data, predictions for the test data are equal for all of the infinitely many parameters (if the linear dependence of the columns is only due to the one-hot encoding).
