### ISSUE TITLE
Sida 31, ekvation 3.21. Teckenbyte?

### ISSUE THREAD

**Issue by MaxSoneback** [uu-sml/sml-book-page#2]
**Location**
Please provide:
1. Draft: January 18, 2020
2. 31
3. 3.21

**Describe the mistake**
Jag tror den första termen, (n/2) * ln(2 * pi * sigma^2), bör vara negativ, då denna term kommer från ln(1/sqrt(2 * pi * sigma^2)) som enligt logaritmregeln ln(a/b) = ln(a) - ln(b).

ln(1/sqrt(2 * pi * sigma^2)) 
= ln(1) - ln(sqrt(2 * pi * sigma^2)) 
= 0 - (1/2) * ln(2 * pi * sigma^2) 

Summerat från 1 till n borde detta alltså bli
(-n/2) * ln(2 * pi * sigma^2)

**Additional comments**
Den här källan verkar stödja mina uträkningar:
https://www.statlect.com/fundamentals-of-statistics/linear-regression-maximum-likelihood#hid4

**Comment by andreas-lindholm** [comment]
Det stämmer, det var uppmärksamt! Kommer vara fixat i nästa version av draft som vi lägger upp.
