### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#20]
**Location**
Please provide:
1. Draft version: October 29, 2020
2. Page number 28
3. Above eq. (3.4)

**Describe the mistake**
"n the prediction"

**Suggested change**
Should be "in the prediction".

**Additional comments**
![sml book n](https://user-images.githubusercontent.com/42183699/98284346-a39f6b00-1fa9-11eb-912e-e2270abe8254.png)

**Comment by nikwa** [comment]
Well spotted, will be updated in the next version.
