### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by timofeymukha** [uu-sml/sml-book-page#21]
**Location**
Please provide:
1. October 29, 2020
2. 105
3. The last sentence

**Describe the mistake**
See: "Recent advances based on deep neural networks have generated algorithms that can learn how to play computer games based on pixel information only (Mnih et al. 2015), how to beat the **would** champion in the board game of Go (Silver et al. 2016) and automatically understand the situation in images for automatic caption generation (K. Xu et al. 2015)."

**Suggested change**
Should be "beat the *world* champion".

**Comment by nikwa** [comment]
Thanks, will be updated in the next version.
