### ISSUE TITLE
Graph Description in Example 3.5

### ISSUE THREAD

**Issue by olilonq** [uu-sml/sml-book-page#22]
**Location**
Please provide:
1. Version (bottom left page)
Draft version: October 29, 2020
2. Page number
41
3. Line/equation number
Last section of Example 3.5

**Describe the mistake**
The description of the different color functions in the graph is not the same as the actual colors in the graph

Description vs Graph
Plain Linear Regression - Described as Blue Dashed, is in fact Blue Solid in Graph
Second Order Polynomial - Described as Blue Solid, is in fact Red Solid in Graph
10th Order Polynomial - Described as a Red Solid, is in fact a Green Solid

**Suggested change**
Adjust the description so that it describes the graph correctly.

**Additional comments**

**Comment by andreas-lindholm** [comment]
Fixed
