### ISSUE TITLE
Green in text but blue in image

### ISSUE THREAD

**Issue by staffannoteberg** [uu-sml/sml-book-page#23]
**Location**
Please provide:
1. Version (bottom left page)
2. Page number 55
3. Line/equation number Line 4 in example 4.1

**Describe the mistake**
Please let us know what is wrong

Image has blue and red dots. Text says green and red dots.

**Suggested change**
If you have an idea on how to fix it, please let us know

s/green/blue in text

**Additional comments**

Like the book. Keep up the good work.

![Screenshot_20201128-085757_Moon+ Reader](https://user-images.githubusercontent.com/185231/100496850-da574400-3157-11eb-8679-7a6735b9aad3.jpg)

**Comment by andreas-lindholm** [comment]
Well spotted, thanks! Will be fixed in next version
