### ISSUE TITLE
Small mistakes

### ISSUE THREAD

**Issue by stumar93** [uu-sml/sml-book-page#24]
**Location**

**1. Version (bottom left page)**
Draft (November 22, 2020)

**2. Page number**
98

**3. Line/equation number**
Last paragraph example 6.1

**Describe the mistake and suggested change**
See highlight areas in figure
![image](https://user-images.githubusercontent.com/43165200/101479859-23c34280-3953-11eb-8faf-cfe8f3b62e2b.png)

**Comment by nikwa** [comment]
Thanks! Will be updated in next version!
