### ISSUE TITLE
Typos in chapter 9

### ISSUE THREAD

**Issue by timofeymukha** [uu-sml/sml-book-page#25]
**Location**
Please provide:
1. Version: November 22.
2.  Page 153, the beginning of Chapter 9.
3. Last sentence in the second paragraph.

**Describe the mistake**

> We thereafter go back to basics and **applies** the Bayesian approach to linear regression, which we thereafter extend to the
> **non-arametric** Gaussian process model.

**Suggested change**
Should be appl**y** (since "we") and non-**p**arametric

**Comment by andreas-lindholm** [comment]
Thanks, will be updated in the next version!
