### ISSUE TITLE
"on the form"

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#26]
**Location**
Please provide:
1. Version (bottom left page): Draft (November 22, 2020) of Supervised Machine Learning.
2. Page number: 71, 96, 99
3. Line/equation number: It is easier just to search for the text "on the form".

**Describe the mistake**
I assume the correct version would be "of the form", i.e. replace "on" with "of".

**Suggested change**
Described above.

**Additional comments**
No.

**Comment by nikwa** [comment]
I agree with you, that is a more correct wording. Will be updated in next version. Thanks!
