### ISSUE TITLE
Typo "as outline above"

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#27]
**Location**
Please provide:
1. Version (bottom left page):  Draft (November 22, 2020) of Supervised Machine Learning
2. Page number: 100
3. Line/equation number: Please see a picture attached.
![image](https://user-images.githubusercontent.com/42183699/101765371-e513c080-3ae9-11eb-9159-bf709db26461.png)

**Describe the mistake**
"as outline above" -> "as outlineD above".

**Suggested change**
Described above.

**Additional comments**
No.

**Comment by nikwa** [comment]
Thanks! Will be updated in next version.
