### ISSUE TITLE
Standardization of the feature matrix before fitting a regularized regression

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#29]
Please consider a short discussion (Chapter 5.4 Regularization) of whether or not the feature matrix should be standardized before fitting a regularized regression, such as Ridge or Lasso. The [original article](https://statweb.stanford.edu/~tibs/lasso/lasso.pdf) seems to assume standardization in the definition and all examples. The [scicit-learn documentation](https://scikit-learn.org/stable/modules/linear_model.html#practical-considerations) mentions standardization as a practical consideration. This was not obvious to me when first time reading about regularization.
Thank you for a great book and for considering this suggestion!

**Comment by andreas-lindholm** [comment]
Good point. We will take this into consideration for future updates.
