### ISSUE TITLE
Fel siffror på y-axel?

### ISSUE THREAD

**Issue by maly6600** [uu-sml/sml-book-page#3]
Sid 39, Fig 3.4: Står i bildtexten att "y = -1 or 1" men i grafen så är värdena på y-axeln (vertikala axeln) mellan 1 och 0.

**Comment by andreas-lindholm** [comment]
Figuren är korrekt. Den vertikala axeln i bilden visar inte y, utan g(x) (som ligger mellan 0 och 1, eftersom det är sannolikheten för att y=1).
