### ISSUE TITLE
Covariance matrix for LDA

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#30]
**Location**
Please provide:
1. Version (bottom left page): November 22, 2020
2. Page number: 195
3. Line/equation number: Equation (11.3c)

**Describe the mistake**
The scaling factor is 1/n_m.

**Suggested change**
In other sources (e.g. https://www.stat.cmu.edu/~larry/=sml/linearclassification.pdf) it is 1/(n_m-1). So I am wondering if the equation (11.3c) is missing "-1".

**Additional comments**
No.

**Comment by devmotion** [comment]
Both versions are correct, they only use different estimators of the covariance matrix. Both estimators are consistent, i.e., if the number of samples `n_m` goes to infinity, both estimates converge to the true covariance matrix. The estimator with `1/(n_m-1)` is unbiased, i.e., for a fixed finite sample size repeated estimation with different randomly sampled datasets would yield the true value on average, whereas the estimator with `1/n_m` is biased, i.e., does not satisfy this property. The correction factor `n_m/(n_m - 1)` is known as [Bessel's correction](https://en.m.wikipedia.org/wiki/Bessel%27s_correction). By the way, often the unbiased estimator has a larger mean squared error than the biased estimator.

**Comment by dmitrijsk** [comment]
Thank you for a detailed answer! Is there a specific reason for choosing a biased estimator in this case?

**Comment by andreas-lindholm** [comment]
The reason is that we want to give a consistent framework with the semi-
and unsupervised use of the GMM model later in the same chapter. For most
practical use cases, I think the choice of covariance matrix estimator
doesn't really matter for LDA.

Den lör 2 jan. 2021 12:43Dmitrijs Kass <notifications@github.com> skrev:

**Comment by dmitrijsk** [comment]
Thank you!
