### ISSUE TITLE
Non consistent referencing

### ISSUE THREAD

**Issue by arakrax** [uu-sml/sml-book-page#31]
**Location**
1. Version: Draft November 22, 2020
2. Page 194
3. Section above and below heading 'Supervised learning of the Gaussian mixture model'.

**Describe the mistake**
When referencing the model '11.1' is used and not '11.1a'. This makes for a less coherent text since the Gaussian distribution in the same paragraph is referenced with '11.1b'. Also it may confuse readers to which 11.1 (a-c) is referenced.

**Suggested change**
Change all references to equation '11.1a' from '11.1' to '11.1a'

**Additional comments**
NIL

**Comment by andreas-lindholm** [comment]
A reference to (1.11) are to be read as a reference to the equations (1.11a-c) altogether, which I believe is a common practice. We never intend to reference (1.11a) only.
