### ISSUE TITLE
"method a method"

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#32]
**Location**
Please provide:
1. Version (bottom left page): November 22
2. Page number: 54
3. Line/equation number: Please see a picture below:

![image](https://user-images.githubusercontent.com/42183699/103442395-6b8d6f00-4c5e-11eb-8ac6-decc4b8be255.png)

**Describe the mistake**
Duplicate word "method".

**Comment by nikwa** [comment]
Thanks! Will be updated in the next version!
