### ISSUE TITLE
Typo, Eq 6.21

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#35]
**Location**
Please provide:
1. Version (bottom left page): November 22
2. Page number: 99
3. Line/equation number: Eq 6.21

**Describe the mistake**
t=1,2,...

**Suggested change**
I think `t` should start from 0 to connect step 1 with `theta_0` and step 2.

**Comment by nikwa** [comment]
Yes, you are correct. Will be updated in next version! Thanks!
