### ISSUE TITLE
Typo in Chapter 3

### ISSUE THREAD

**Issue by shubhomoy** [uu-sml/sml-book-page#36]
**Location**
1. Version: January 4, 2021
2. Page number: 38
3. Line/equation: First paragraph, the second line just below Figure 3.4

**Describe the mistake**
> For such a problem, minimizing the misclassification rate might **lead** not lead to the desired performance

**Suggested change**
> For such a problem, minimizing the misclassification rate might not lead to the desired performance

**Additional comments**
There is an extra "lead"

**Comment by andreas-lindholm** [comment]
Thanks! Will be fixed in next version
