### ISSUE TITLE
Spelling mistakes in chapters 6 and 7

### ISSUE THREAD

**Issue by posterrieri** [uu-sml/sml-book-page#37]
**Version January 12, 2021**

I've found some mistakes, and tried to provide some fixes where I could.

- Chapter 7.3, page 128
1.  which base classifier to use, an -> which base classifier to use, and
2.  terminal nodes often works -> terminal nodes often work
3. nature of boosting it -> nature of boosting is

- Chapter 6.3, page 104
1. Section 6.1 and 6.1

**Comment by andreas-lindholm** [comment]
Thanks, they will be corrected in the next version!
