### ISSUE TITLE
Typo "applies"

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#39]
**Location**
Please provide:
1. Version (bottom left page): Draft version: January 12, 2021
2. Page number: 153
3. Line/equation number: Image below.

![image](https://user-images.githubusercontent.com/42183699/106018788-97b7d680-60ca-11eb-9ff3-84dd2c5387cc.png)

**Describe the mistake**
"applies" -> "apply"
"non-arametric" -> "non-parametric"

**Comment by nikwa** [comment]
Will be implemented in next version. Thanks!
