### ISSUE TITLE
Mistake in matrix?

### ISSUE THREAD

**Issue by maly6600** [uu-sml/sml-book-page#4]
**Location**
Please provide:
1. Version: Jan 18
2. Page number: 37
3. Text box: Example 3.5

**Describe the mistake**
First column in matrix called **G** doesn't read right. It has inputs: x_1, x_2, x_5(!) and so on to the g(x)-function.

**Comment by andreas-lindholm** [comment]
Indeed a typo, will be fixed in next version. Thanks!
