### ISSUE TITLE
Red dots and lines in Example 9.1: Bayesian linear regression

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#40]
**Location**
Please provide:
1. Version (bottom left page): Draft version: January 12, 2021
2. Page number: 158
3. Line/equation number: Example 9.1: Bayesian linear regression

**Describe the mistake**
There are no red dots and no red lines on the plots in Example 9.1: Bayesian linear regression.

**Comment by nikwa** [comment]
Will be corrected in next version. Thanks!
