### ISSUE TITLE
Wordy sentence on page 43

### ISSUE THREAD

**Issue by terratrends** [uu-sml/sml-book-page#43]
On page 42 there is a wordy senctence:  "to carefully select which inputs (transformations) to include, and which that should not be part of the model."

Perhaps replace with something like "to carefully select the inputs (transformations) to be included."

or

"to carefully select the inputs (transformations) to be included while excluding inputs less optimal for training the model."

**Comment by nikwa** [comment]
Will be implemented in next version. Thanks!
