### ISSUE TITLE
Typo in chapter 8

### ISSUE THREAD

**Issue by timofeymukha** [uu-sml/sml-book-page#44]
**Location**
Please provide:
1. March 3, 2021
2. 158
3. Last line in the second paragraph, right above Example 8.2

**Describe the mistake**
"We will also come back to kernel ridge regression in Chapter 9, where it is used as a stepping stone in deriving the Gaussian process **_regresison_** model

**Suggested change**
Should be "regression"

**Comment by andreas-lindholm** [comment]
Thanks!
