### ISSUE TITLE
 Possible error in the concept of Pooling layer

### ISSUE THREAD

**Issue by reubensajith** [uu-sml/sml-book-page#46]
**Location**
Please provide: Erratum 1

1. Draft (April 30, 2021) of Machine Learning
2. Page 127
3. Second line below Figure 6.13

**Describe the mistake**
It is mentioned as "In max pooling we instead take the average of the pixels."

**Suggested change**
We take the average of the units in average pooling. In max pooling, we take the maximum value among the pixels within the pooling filter.

![Screenshot 2021-06-02 at 07 47 45](https://user-images.githubusercontent.com/60505767/120430134-d4485700-c376-11eb-97c7-bdd34c3e53d6.png)

**Location**
Please provide: Erratum 2

1. Draft (April 30, 2021) of Machine Learning
2. Page 127
3. Fifth line below Figure 6.13

**Describe the mistake**
<Typo> It is mentioned as "to small translations of the input mkeaning if we translate the input by a small amount"

**Suggested change**
"to small translations of the input meaning if we translate the input by a small amount"

**Location**
Please provide: Erratum 3

1. Draft (April 30, 2021) of Machine Learning
2. Page 128
3. Second line under the topic "Full CNN architecture"

**Describe the mistake**
<Typo> It is mentioned as "number of rows and columns in the hidden layers as we proceed though the network"

**Suggested change**
"number of rows and columns in the hidden layers as we proceed through the network"

**Comment by andreas-lindholm** [comment]
Thank you!
