### ISSUE TITLE
Figure references in wrong format

### ISSUE THREAD

**Issue by simoncarlen** [uu-sml/sml-book-page#49]
**Location**
Please provide:
1. April 30, 2021
2. Page 22, 24 and 74
3. Example 2.3, 2.4 and 4.4. 
In example 2.3 and 2.4: in the text just under Figure 2.3 and Figure 2.4
In example 4.4: line 2 in the example box.

**Describe the mistake**
Figure references in the text are in the wrong format, see attached pictures. 

**Additional comments**
<img width="610" alt="Skärmavbild 2021-07-07 kl  10 41 25" src="https://user-images.githubusercontent.com/58792021/124729596-df138000-df10-11eb-9ae7-bb34c3cc596a.png">
<img width="605" alt="Skärmavbild 2021-07-07 kl  10 41 36" src="https://user-images.githubusercontent.com/58792021/124729603-dfac1680-df10-11eb-8f3d-26a902a017db.png">
<img width="822" alt="Skärmavbild 2021-07-08 kl  09 22 09" src="https://user-images.githubusercontent.com/58792021/124880211-54915600-dfce-11eb-974b-1aaaa8a6c785.png">

**Comment by andreas-lindholm** [comment]
thanks!
