### ISSUE TITLE
Fel i formel?

### ISSUE THREAD

**Issue by maly6600** [uu-sml/sml-book-page#5]
**Location**
Please provide:
1. Draft (January 25, 2020)
2. Page number: 62
3. Table 4.1

**Describe the mistake**
Står:
(TN+TP)/n = Misclassification rate                       

**Suggested change**
(FN+FP)/n = Misclassification rate   

**Additional comments**
Om det är ett fel, så står det också fel på raden under.

**Comment by andreas-lindholm** [comment]
Det stämmer, kommer att vara uppdaterat i nästa version. Tack!!
