### ISSUE TITLE
Word missing in Example 4.5

### ISSUE THREAD

**Issue by simoncarlen** [uu-sml/sml-book-page#50]
**Location**
Please provide:
1. April 30, 2021
2. Page 77
3. Line 9 in example box 4.5

**Describe the mistake**
"Hence, the naive (and useless) classifier which always predicts will obtain a misclassification rate of around 7%."

**Suggested change**
I believe the word **normal** is missing, change to:

"Hence, the naive (and useless) classifier which always predicts ***normal*** will obtain a misclassification rate of around 7%."

**Comment by andreas-lindholm** [comment]
Thank you
