### ISSUE TITLE
Inconsistent Theorem Numbering in chapter 9 

### ISSUE THREAD

**Issue by MohammedAlJaff** [uu-sml/sml-book-page#51]
**Location**
Please provide: 
1. Version: April 30, 2021
2. Page number: 201
3. Line/equation/Figure number:  Figure 9.15

**Describe the mistake**
The theorem numberings for the 'transition theorems'  between the the joint, marginal and conditional distributions in figure 9.15 deviate from the theorem numberings on the same page ('Off by one' numbering mistake).

**Additional comments**
Make explicit  that equation 9.1 is also theorem 9.1 like how Theorems 9.2 -9.4 are defined explicitly as theorems.

**Comment by andreas-lindholm** [comment]
Thank you!
