### ISSUE TITLE
Typos in chapter 6

### ISSUE THREAD

**Issue by simoncarlen** [uu-sml/sml-book-page#53]
**Location**
Please provide:
1. April 30, 2021
2. Page 113, 114, 116, 118, 123
3. p. 113: fourth line under 'Generalized linear regression', 
p. 114: The figure text for Figure 6.1, 
p. 116: first line just under eq. 6.10, 
p. 118: Line 8 from bottom in Example 6.1, 
p. 123: Line 2 in Example 6.2

**Describe the mistake**
p. 113: "we will later handle the weights ***sightly*** differently"
p. 114: In the figure text it says " the output z", but the output should be y (hat)
p. 116: "This means that the layers are stacked such that the output ***of from*** the first layer of hidden units q"
p. 118: "That is identical to a neural network with ***just only layer***, that means (6.16) where L = 1."
p. 123: "Based on the presented data we train the two models mentioned in end of that example"

**Suggested change**
p. 113: sightly --> slightly
p. 114: change to y (hat) in figure text
p. 116: Maybe remove "from"
p. 118: Change to "just one layer", or "only one layer"
p. 123: "Based on the presented data we train the two models mentioned in ***the*** end of that example"

**Comment by andreas-lindholm** [comment]
Thank you
