### ISSUE TITLE
Chapter 9.1 Latex typo

### ISSUE THREAD

**Issue by venz97** [uu-sml/sml-book-page#57]
**Location**
Please provide: [p.183]
**Version: Draft April 30, 2021**
Page number: 183
**Describe the mistake**
![bugg](https://user-images.githubusercontent.com/49234497/132220433-b1cfe07a-4a50-49e7-8e96-ea3672fc1274.PNG)
Latex error "y_star"

**Suggested change**
y_{/star} would probably fix the error

Additional comments

**Comment by andreas-lindholm** [comment]
thanks!
