### ISSUE TITLE
Figure fig:ex:knn1

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#58]
**Location**
Please provide:
1. Version (bottom left page): Draft (April 30, 2021)
2. Page number: 21
3. Line/equation number : see image below.

**Describe the mistake**
Figure number not rendered.

![image](https://user-images.githubusercontent.com/42183699/140833566-7900974f-3e73-4bc2-906f-3e4f08f0461a.png)

**Comment by dmitrijsk** [comment]
Same on page 24:
![image](https://user-images.githubusercontent.com/42183699/140834046-d72eb1c3-5986-42ed-9447-2cabc6decdc7.png)

**Comment by andreas-lindholm** [comment]
Thank you, this has now been updated.
