### ISSUE TITLE
Fel i formel?

### ISSUE THREAD

**Issue by maly6600** [uu-sml/sml-book-page#6]
**Location**
Please provide:
1. Version: Jan 25
2. Page number: 133
3. Line/equation number: 11.1c, 11.1d

**Describe the mistake**
p(x|y=1) = pi_1
p(x|y=M)= pi_M

**Suggested change**
p(y=1) = pi_1
p(y=M)= pi_M

**Additional comments**
Eftersom det är p(y) som ska modelleras.

**Comment by nikwa** [comment]
Indeed a typo, it has now been fixed in updated version on the homepage. Thanks!
