### ISSUE TITLE
argmin in eq. 2.6

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#67]
**Location**
Please provide:
1. Version (bottom left page) Draft (April 30, 2021)
2. Page number 30
3. Line/equation number eq. 2.6

**Describe the mistake**
I think we are not really interested in the exact minimum value of the cost `n_1Q_1+n_2Q_2`. We are interested in `j` and `s` that give the minimum cost. Therefore, wouldn't `argmin` be more suitable instead of a `min`?

**Comment by andreas-lindholm** [comment]
I agree. This has now been updated.
