### ISSUE TITLE
"effects" should be "affects" on p 73

### ISSUE THREAD

**Issue by tmlouw** [uu-sml/sml-book-page#68]
**Location**
Please provide:
1. Version (bottom left page): **draft April 30, 2021**
2. Page number **73**
3. Line/equation number **approximately middle of the page**

**Describe the mistake**
There is a sentence in parentheses: "(This effects also the training error and the generalization gap, but in a less clear way.)". The word "effects" should be "affects", and I believe the period should be outside the parentheses.

**Suggested change**
"(This affects also the training error and the generalization gap, but in a less clear way)."

**Additional comments**

**Comment by andreas-lindholm** [comment]
Thank you, this has now been updated.
