### ISSUE TITLE
Change symbol "gamma" in Example 4.4, to "lambda"

### ISSUE THREAD

**Issue by tmlouw** [uu-sml/sml-book-page#69]
In Example 4.4 on p 74, you use the Greek symbol "gamma" to indicate the regularization parameter. Earlier in the book (and in line with most discussions on regularization), the Greek symbol "lambda" is used. My suggestion is simply to change the symbol "gamma" to "lambda" in Example 4.4.

**Comment by andreas-lindholm** [comment]
Good suggestion, this has now been updated
