### ISSUE TITLE
Page 12 | Possible error in Example 2.2

### ISSUE THREAD

**Issue by reubensajith** [uu-sml/sml-book-page#7]
**Location**
Please provide:
1. Draft (January 25, 2020) of Supervised Machine Learning
2. Page 12
3. Example 2.2

**Describe the mistake**
<img width="485" alt="Screenshot 2020-01-31 at 10 52 56 AM" src="https://user-images.githubusercontent.com/60505767/73531377-9ea9fb80-441a-11ea-9561-7213391f989d.png">

I noticed an ambiguity that you might take into consideration. The underlined text explains that the table is to be sorted in descending order. But the table is sorted in ascending order with respect to the euclidean value.

**Comment by nikwa** [comment]
Yes, you are correct. Will be corrected.
