### ISSUE TITLE
Grammar error below log-likelihood equation on p 84

### ISSUE THREAD

**Issue by tmlouw** [uu-sml/sml-book-page#70]
**Location**
Please provide:
1. Version (bottom left page) **Draft, April 2021**
2. Page number **84**
3. Line/equation number **Directly below the negative log-likelihood equation**

**Describe the mistake**
Minor grammar mistake: "Once the parameters have been learning,..." should read "Once the parameters have been learnt"

**Suggested change**
"Once the parameters have been learning,..." should read "Once the parameters have been learnt"

**Additional comments**

**Comment by andreas-lindholm** [comment]
Thank you, this has now been updated.
