### ISSUE TITLE
Wrong superscript in eq. (6.16b)

### ISSUE THREAD

**Issue by dgedon** [uu-sml/sml-book-page#71]
**Location**
Please provide:
1. Version: Draft (April 30, 2021)
2. Page number: 118
3. Line/equation number: eq. (6.16b)

**Describe the mistake**
On page 118 in eq. (6.16b) the bias term b should have superscript (L-1) instead of superscript (1)

**Suggested change**
change the superscript to (L-1) instead of (1)

**Additional comments**
Mistake identified by student Brigitta Selb in SML course at UU.

**Comment by andreas-lindholm** [comment]
Thank you, this has now been updated.
