### ISSUE TITLE
Punctuation around "say"

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#72]
**Location**
Please provide:
1. Version (bottom left page) Draft (April 30, 2021)
2. Page number 126
3. Line/equation number please see an image below.

**Describe the mistake**
I think "say" should be surrounded by commas.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/42183699/146283461-055fc240-0b13-4b2a-92d7-fe9371084505.png">

**Comment by andreas-lindholm** [comment]
Thank you, this has now been updated.
