### ISSUE TITLE
Typo in "mkeaning"

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#73]
**Location**
Please provide:
1. Version (bottom left page): Draft (April 30, 2021)
2. Page number: 127
3. Line/equation number: please see an image below.

**Describe the mistake**
mkeaning

**Suggested change**
meaning

<img width="591" alt="image" src="https://user-images.githubusercontent.com/42183699/146287854-2928dde1-01e0-4985-9f0a-12cc674b05a0.png">

**Comment by andreas-lindholm** [comment]
Thank you, this has now been updated.
