### ISSUE TITLE
Publish book errata

### ISSUE THREAD

**Issue by Krisell** [uu-sml/sml-book-page#76]
I know that you mention on the book website that while being published, no updates will be made. However I think a compiled list of confirmed errata would be helpful. While reading through the book, I noticed some obvious and some potential typos/errors and after doing some work to collect a few (screenshots), I found them all as separate issues here on GitHub. An errata list would both confirm what is the intended meaning/spelling, and also save readers time.

**Comment by andreas-lindholm** [comment]
Thank you for your interest in the book. It was a good suggestion, but unfortunately we never had the time to implement it. But we have now finally updated the PDF after the publishers copyediting process, so I hope this is not relevant anymore and that most typos are gone now.
