### ISSUE TITLE
Small typo p.86

### ISSUE THREAD

**Issue by tureture** [uu-sml/sml-book-page#78]
**Location**
Please provide:
1. Version (bottom left page) Draft (April 30, 2021)
2. Page number p.86
3. Line/equation number,  around 8 lines below figure 5.20 

**Describe the mistake**
Small typo in the text a couple sentences below figure 5.20
"We can therefore tell from Figure 5.2 that the exponential loss is expected to **by** sensitive to outliers

**Suggested change**
Change from "by" to "be" 

**Additional comments**

**Comment by andreas-lindholm** [comment]
Thank you, this has now been updated.
