### ISSUE TITLE
"Lunch cancer" instead of "lung cancer"

### ISSUE THREAD

**Issue by MojaPoya** [uu-sml/sml-book-page#79]
**Location**
Please provide:
1. Draft version: April 30, 2021
2. page, 13
3. "Recent estimates indicate that 4.2 million people die each
year as a result of ambient air pollution due to stroke, heart disease, lunch cancer and chronic respiratory
diseases."

Second line of that page.

**Describe the mistake**
It sais lunch cancer 

**Suggested change**

Change word to lung cancer

**Additional comments**

**Comment by andreas-lindholm** [comment]
Thank you, this has now been updated.
