### ISSUE TITLE
Litet misstag i figur, två olika konstanter som borde vara samma

### ISSUE THREAD

**Issue by Skapinka** [uu-sml/sml-book-page#8]
**Location**
1. Version: 31 januari 2020
2. Sida 48
3. Figur 4.2

**Describe the mistake**
Först beskrivs "for l = 1, ... , k", men sedan används "l = 1" till "l = c" bredvid figurerna på datan.

**Suggested change**
Ändra c till k

**Comment by nikwa** [comment]
Yes, tat is a typo. Thanks!
