### ISSUE TITLE
max pooling vs average

### ISSUE THREAD

**Issue by dmitrijsk** [uu-sml/sml-book-page#80]
**Location**
Please provide:
1. Draft (April 30, 2021) of Machine Learning – A First Course for Engineers and Scientists. http://smlbook.org
2. Page number 127
3. Line/equation number Top paragraph

**Describe the mistake**
In max pooling we instead take the average of the pixels.

**Suggested change**
Should be "max" instead of the "average"

**Comment by andreas-lindholm** [comment]
Thank you, this has now been updated
