### ISSUE TITLE
Invalid Parentheses

### ISSUE THREAD

**Issue by nanguoyu** [uu-sml/sml-book-page#9]
**Location**
Please provide:
1. Version  : January 31, 2020
2. Page number : 18
3. Line/equation number The third line after "Classification trees"

**Describe the mistake**
Invalid Parentheses

$$\widehat{y}_{m}=\text { Majority Vote }\left\{[\} y_{i}: \mathbf{x}_{i} \in R_{\ell}\right]$$

**Suggested change**

**Additional comments**

**Comment by nikwa** [comment]
Yes, that is a typo. Thanks!
